### ISSUE TITLE
Strange test result involving infinity

### ISSUE THREAD

**Issue by arstrube** [cpputest/cpputest#704] opened 2015-07-15 09:22 UTC
Given the following test:
```c++
DOUBLES_EQUAL(std::numeric_limits<double>::infinity(), 1.0d / 0.0d, 0.0d);
```
I get the following result:
```c++
expected <inf>
but was  <inf> threshold used was <0>
```
The problem does not seem related to the threshold used, e.g. it will not go away with, say, a threshold of 1.0d.

The same strange result is obtained by doing simply:
```c++
DOUBLES_EQUAL(1.0d / 0.0d, 1.0d / 0.0d, 0.0d);
```

**Comment by arstrube** [comment] 2015-07-15 09:31
A bit strange is also the following:
```c++
DOUBLES_EQUAL(5.1d, 15.3d / 3.0d, 0.0d);
```
which yields:
```c++
expected <5.1>
but was  <5.1> threshold used was <0>
```
There is indeed a tiny difference, and the FE_INEXACT flag is set -- however, why is the floating point number not printed in such a way, that the difference is shown? Like:
```c++
expected <5.1>
but was  <5.0999999993>
```
or whatever.

**Comment by jgonzalezdr** [comment] 2015-07-15 10:02
The problem is in the algorithm used to compare doubles, because they are subtracted then compared against the threshold, but subtraction of (inf) - (inf) is indeterminate...

I propose a fix for that in #705.

**Comment by arstrube** [comment] 2015-07-15 11:09
Wow. That was fast :) 

It occurred to me that we might need PlatformSpecificIsInf() for that... Thanks!

**Comment by jgonzalezdr** [comment] 2015-07-15 11:18
I already knew the problem because I found it in the past, but the tests finally didn't need to check infinity so I never wrote a fix. 

Regarding the precision of printed doubles, I'm with you that I should be fixed, otherwise it's hard to spot where the problem is.

**Comment by basvodde** [comment] 2015-08-07 23:44
Solved by PR. Closing issue.

**Closed by basvodde** 2015-08-07 23:44 UTC
