### ISSUE TITLE
VC98 compilation broken

### ISSUE THREAD

**Issue by PaulBussmann** [cpputest/cpputest#482] opened 2015-02-09 14:00 UTC
The Visual Studio support for VC98 seems broken.

The following patch fixes this issue:

diff --git a/CppUTest.dsp b/CppUTest.dsp
index 6872242..3868bb4 100644
--- a/CppUTest.dsp
+++ b/CppUTest.dsp
@@ -41,7 +41,7 @@ RSC=rc.exe
 # PROP Intermediate_Dir "Release"
 # PROP Target_Dir ""
 # ADD BASE CPP /nologo /W3 /GX /O2 /D "WIN32" /D "NDEBUG" /D "_MBCS" /D "_LIB" /YX /FD /c
-# ADD CPP /nologo /W3 /GX /O2 /D "WIN32" /D "NDEBUG" /D "_MBCS" /D "_LIB" /YX /FD /c
+# ADD CPP /nologo /W3 /GX /O2 /I ".\include\Platforms\VisualCpp" /I ".\include" /D "WIN32" /D "NDEBUG" /D "_MBCS" /D "_LIB" /YX /FD /c
 # ADD BASE RSC /l 0x409 /d "NDEBUG"
 # ADD RSC /l 0x409 /d "NDEBUG"
 BSC32=bscmake.exe
@@ -64,7 +64,7 @@ LIB32=link.exe -lib
 # PROP Intermediate_Dir "Debug"
 # PROP Target_Dir ""
 # ADD BASE CPP /nologo /W3 /Gm /GX /ZI /Od /D "WIN32" /D "_DEBUG" /D "_MBCS" /D "_LIB" /YX /FD /GZ /c
-# ADD CPP /nologo /MDd /W3 /GX /ZI /Od /I ".\include\Platforms\VisualCpp" /I ".\include\CppUTest" /D "WIN32" /D "_DEBUG" /D "_MBCS" /D "_LIB" /FD /GZ /c
+# ADD CPP /nologo /MDd /W3 /GX /ZI /Od /I ".\include\Platforms\VisualCpp" /I ".\include" /D "WIN32" /D "_DEBUG" /D "_MBCS" /D "_LIB" /FR /FD /GZ /c
 # SUBTRACT CPP /YX
 # ADD BASE RSC /l 0x409 /d "_DEBUG"
 # ADD RSC /l 0x409 /d "_DEBUG"
@@ -90,14 +90,6 @@ SOURCE=.\SRC\CPPUTEST\CommandLineTestRunner.cpp
 # End Source File
 # Begin Source File
 
-SOURCE=.\SRC\CPPUTEST\EqualsFailure.cpp
-# End Source File
-# Begin Source File
-
-SOURCE=.\SRC\CPPUTEST\Failure.cpp
-# End Source File
-# Begin Source File
-
 SOURCE=.\SRC\CPPUTEST\JUnitTestOutput.cpp
 # End Source File
 # Begin Source File
@@ -106,26 +98,14 @@ SOURCE=.\SRC\CPPUTEST\MemoryLeakWarningPlugin.cpp
 # End Source File
 # Begin Source File
 
-SOURCE=.\SRC\CPPUTEST\NullTest.cpp
-# End Source File
-# Begin Source File
-
 SOURCE=.\SRC\CPPUTEST\SimpleString.cpp
 # End Source File
 # Begin Source File
 
-SOURCE=.\SRC\CPPUTEST\SimpleStringExtensions.cpp
-# End Source File
-# Begin Source File
-
 SOURCE=.\SRC\CPPUTEST\TestHarness_c.cpp
 # End Source File
 # Begin Source File
 
-SOURCE=.\SRC\CPPUTEST\TestInstaller.cpp
-# End Source File
-# Begin Source File
-
 SOURCE=.\SRC\CPPUTEST\TestOutput.cpp
 # End Source File
 # Begin Source File
@@ -148,10 +128,6 @@ SOURCE=.\SRC\CPPUTEST\Utest.cpp
 
 SOURCE=.\src\Platforms\VisualCpp\UtestPlatform.cpp
 # End Source File
-# Begin Source File
-
-SOURCE=.\src\Platforms\VisualCpp\Win32MemoryLeakWarning.cpp
-# End Source File
 # End Group
 # Begin Group "Header Files"
 
diff --git a/include/Platforms/VisualCpp/Platform.h b/include/Platforms/VisualCpp/Platform.h
index d208ee6..45f662f 100644
--- a/include/Platforms/VisualCpp/Platform.h
+++ b/include/Platforms/VisualCpp/Platform.h
@@ -26,16 +26,16 @@
  */
 
 #ifdef _MSC_VER
-//#pragma warning(disable:4786)
-//#pragma warning(disable:4290)
-//#pragma warning(disable:4996)
+#pragma warning(disable:4786)
+#pragma warning(disable:4290)
+#pragma warning(disable:4996)
 #endif
 
 #ifdef WIN32
     #ifdef _VC80_UPGRADE
-        //#pragma warning(disable:4996)
-        //#pragma warning(disable:4290)
+        #pragma warning(disable:4996)
+        #pragma warning(disable:4290)
     #else
-        //#define vsnprintf _vsnprintf
+        #define vsnprintf _vsnprintf
     #endif
 #endif
diff --git a/src/Platforms/VisualCpp/UtestPlatform.cpp b/src/Platforms/VisualCpp/UtestPlatform.cpp
index 7b4da7f..d52380e 100644
--- a/src/Platforms/VisualCpp/UtestPlatform.cpp
+++ b/src/Platforms/VisualCpp/UtestPlatform.cpp
@@ -73,7 +73,7 @@ static const char* TimeStringImplementation()
     time_t the_time = time(NULL);
     struct tm the_local_time;
     static char dateTime[80];
-    localtime_s(&the_local_time, &the_time);
+    _getsystime(&the_local_time);
     strftime(dateTime, 80, "%Y-%m-%dT%H:%M:%S", &the_local_time);
     return dateTime;
 }
@@ -87,7 +87,7 @@ int PlatformSpecificVSNprintf(char *str, size_t size, const char* format, va_lis
     char* buf = 0;
     size_t sizeGuess = size;
 
-    int result = _vsnprintf_s( str, size, _TRUNCATE, format, args);
+    int result = _vsnprintf( str, size, format, args);
     str[size-1] = 0;
     while (result == -1)
     {
@@ -95,7 +95,7 @@ int PlatformSpecificVSNprintf(char *str, size_t size, const char* format, va_lis
             free(buf);
         sizeGuess += 10;
         buf = (char*)malloc(sizeGuess);
-        result = _vsnprintf_s( buf, sizeGuess, _TRUNCATE, format, args);
+        result = _vsnprintf( buf, sizeGuess, format, args);
     }
 
     if (buf != 0)
@@ -106,8 +106,7 @@ int PlatformSpecificVSNprintf(char *str, size_t size, const char* format, va_lis
 
 PlatformSpecificFile PlatformSpecificFOpen(const char* filename, const char* flag)
 {
-   FILE* file;
-   fopen_s(&file, filename, flag);
+   FILE* file = fopen(filename, flag);
    return file;
 }
 
@@ -165,7 +164,7 @@ extern "C" int (*PlatformSpecificIsNan)(double) = _isnan;
 
 int PlatformSpecificVSNprintf(char *str, unsigned int size, const char* format, void* args)
 {
-   return _vsnprintf_s( str, size, _TRUNCATE, format, (va_list) args);
+   return _vsnprintf( str, size, format, (va_list) args);
 }
 
 static PlatformSpecificMutex Win32MutexCreate(void)

**Comment by arstrube** [comment] 2015-02-09 16:49
Hello Paul,

As far as I know, Visual Studio 2006 is the oldest "supported" version. That said, I don't know whether anyone has that installed. I don't. We test on VS 2008, 2010 and later.

What exactly does VC98 stand for? I'm not really sure what that means.

**Comment by PaulBussmann** [comment] 2015-02-11 08:58
First of all thank you for providing this brilliant piece of software and for your instant support! :)

Motivation to support Visual Studio 6 (VC98):
I got into the redist-hell when I used the CppUTest library on any other PC than it was created on. To solve this I decided to compile with VS6 as it is possible to run the binaries hassle-free (at least) on Windows XP and Windows 7.
VC98 is the compiler shipped with VS6.
I would be glad if VS6 was somehow supported (in sense of reviewing my patch and integrating it). 
To not worry about breaking existing usage, maybe this means creating a modified copy of src/Platforms/VisualCpp/UtestPlatform.cpp to src/Platforms/VisualCpp98/UtestPlatform.cpp and reference this in CppUTest.dsp. Btw. I guess CppUTest.dsp was only meant for VS6 so I'd be happy if you could provide src/Platforms/VisualCpp98/UtestPlatform.cpp together with the CppUTest.dsp for VS6 so it is possible to compile the CppUTest library for systems without need for redists.
CppUTest.dsp seems to be out of maintenance, my proposed patch provides an update to the file according to past refactorings.

**Comment by arstrube** [comment] 2015-02-11 11:10
I think it would be good to make the necessary changes to the .dsp / dsw . This should be done in any case (there seems to be nobody but you able to do it anymore). Perhaps make this a separate pull request. Nobody will mind merging it. (You could maybe cherry pick just those onto a new branch / pull request for starters).

Then about your suggestion with a separate platform directory - I was thinking of that myself but hadn't thought it through. Oviously, we can't just undo the changes we introduced to support more current versions of VC. Conditional compilation might be another route we could take. @basvodde what do you think?

**Comment by basvodde** [comment] 2015-02-12 13:21
Yeah, conditional compilation please ;) I think it should share 95% of the code.

**Comment by arstrube** [comment] 2015-02-17 07:24
@paulbussmann are you planning to do the other changes still? As far as I can tell, it would be mainly about `_vsnprintf_s()` style "safe" functions vs. the old style `_vsnprintf()` functions, right? Perhaps you could wrap those in macros that get defined based on MSVC version? Any other idea?

**Comment by arstrube** [comment] 2015-02-17 07:27
If memory serves me right, the new functions have additional arguments. So if you based the macros on their signature, you could just ignore those for VC98 (and before), right?

**Comment by PaulBussmann** [comment] 2015-02-17 09:03
Conditional implementation according to VC version or "defined functions" with macros/inline functions would be appropriate, I think. I try to provide this as soon as possible, likely within the next days.

**Comment by PaulBussmann** [comment] 2015-02-19 14:28
CppUTest library can be generated with VS6 and linked to applications in VS2005, but there is still the following linker error:
1>CppUTest.lib(MemoryLeakWarningPlugin.obj) : error LNK2001: unresolved external symbol "public: __thiscall std::bad_alloc::bad_alloc(class std::bad_alloc const &)" (??0bad_alloc@std@@QAE@ABV01@@Z)
1>CppUTest.lib(MemoryLeakWarningPlugin.obj) : error LNK2001: unresolved external symbol "public: virtual __thiscall std::bad_alloc::~bad_alloc(void)" (??1bad_alloc@std@@UAE@XZ)
1>CppUTest.lib(MemoryLeakWarningPlugin.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall std::bad_alloc::bad_alloc(char const *)" (__imp_??0bad_alloc@std@@QAE@PBD@Z) referenced in function "void * __cdecl mem_leak_operator_new(unsigned int)" (?mem_leak_operator_new@@YAPAXI@Z)

The linker error about std::bad_alloc can be worked around setting CPPUTEST_MEM_LEAK_DETECTION_DISABLED. 
If there is no way to fix it, I suggest to set CPPUTEST_MEM_LEAK_DETECTION_DISABLED in the VS6 project.

My proposal for conditional compilation is like this:

#ifdef __STDC_WANT_SECURE_LIB__
   FILE* file;
   fopen_s(&file, filename, flag);
#else
   FILE* file = fopen(filename, flag);
#endif

localtime_s, _vsnprintf_s could be macro'ed like this or per usage according to fopen_s (which I'd prefer as it shows conditional secure usage)
///////////// Support VS6 with VC98
#ifndef __STDC_WANT_SECURE_LIB__
#define localtime_s(the_local_time,the_time) _getsystime((the_local_time))
#define _vsnprintf_s(str,size,_TRUNCATE,format,args) _vsnprintf((str),(size),(format),(args))
#endif

I tested building CppUTest lib on Windows XP 32bit, VS6 (VC98) and linking to application in VS2005 on Windows 7.
I tested building with VS2010 does not give compiler errors for conditional compilation.

Please advice so I can finish the sources and request pulling.

**Comment by arstrube** [comment] 2015-02-19 16:16
I would have thought that `#ifdef` for each place where a secure function is called would make for an awful lot of conditional code. Would it be possible to replace those functions by macros, so the `#ifdef` would be only in one place and not everywhere a function is called? Something along the lines of:
```c++
#ifdef STDC_WANT_SECURE_LIB
  #define FOPEN(fp, filename, flag) fopen_s((fp), (filename), (flag))
#else
  #define FOPEN(fp, filename, flag) *(fp) = fopen((filename), (flag))
#endif
```
So the calls would then appear consistantly as
```c++
FILE* file;
FOPEN(&file, filename, flag);
```
I did notice that your approach would be better suited to `localtime_s()`, but then others like `vsnprintf_s()` occur multiple times, so maybe the above approach would be preferable.

**Comment by arstrube** [comment] 2015-02-19 17:22
I would prefer using wrappers for the functions. Something like this in UtestPlatform.cpp would do nicely:
```c++
#ifdef STDC_WANT_SECURE_LIB
    #define FOPEN(fp, filename, flag) fopen_s((fp), (filename), (flag))
    #define _VSNPRINTF(str, size, trunc, format, args) _vsnprintf_s((str), (size), (trunc), (format), (args))
    #define LOCALTIME(_tm, timer) localtime_s((_tm), (timer))
#else
    #define FOPEN(fp, filename, flag) *(fp) = fopen((filename), (flag))
    #define _VSNPRINTF(str, size, trunc, format, args) _vsnprintf((str), (size), (format), (args))
    #define LOCALTIME(_tm, timer) memcpy(_tm, localtime(timer), sizeof(tm));
#endif
```

**Comment by arstrube** [comment] 2015-02-19 17:38
Especially the _vsnprintf() function would look really ugly with per usage conditional compilation.

I was just wondering -- redefining e.g. `localtime_s()` doesn't seem a good idea to me, since that would break on versions of VC that have these functions actually defined. By using wrappers with unique names, I have the choice to not define STDC_WANT_SECURE_LIB even on VC2010 (not that this is necessarily a good choice ;-)

**Comment by arstrube** [comment] 2015-03-09 06:52
@PaulBussmann are you still interested in this being fixed? Please have a look at my pull request #500. Would that work for you?

**Comment by PaulBussmann** [comment] 2015-03-10 10:23
@arstrube and @basvodde thank you very much for your support! 

I was able to build cpputest with your changes. I needed to do small changes. Most problematic are linker error if compiling with MEM_LEAK_DETECTION which I was not able to resolve so I had to add CPPUTEST_MEM_LEAK_DETECTION_DISABLED.

I committed all my changes to https://github.com/PaulBussmann/cpputest and the commits are isolated:

Added unreferenced cpp-files needed to build cpputest.lib
https://github.com/PaulBussmann/cpputest/commit/2a6521c1f173695204823d9189162430e9281878

Fix compilation issue with VS6
https://github.com/PaulBussmann/cpputest/commit/378bc3711a0879f5fb2be90fa15cfbf71f98ca62

Adding CPPUTEST_MEM_LEAK_DETECTION_DISABLED to VS6 project
https://github.com/PaulBussmann/cpputest/commit/5cc6186ec6eaa88b428dce69c5b9cbe9bbfbdd12

Should I create a pull request for https://github.com/cpputest/cpputest ?

**Comment by basvodde** [comment] 2015-03-11 01:22
@arstrube Usually we try to support all platforms that have somewhat of a C++ compiler :) Not always with project files, but at least the code ought to compile with whatever C++ compiler.

@PaulBussmann Pull requests will do. However, you should be able to get the memory leak detector to work on VS6. The very very old original version of it was build in VS6 15 years ago :) So, there should be another way to deal with the linker error (though I don't remember what)

**Comment by arstrube** [comment] 2015-03-11 06:59
@PaulBussmann - I tried to set up VC6 in my VM last night. Will need a second attempt. Meanwhile, are you sure you did a full rebuild with -O0 when you tried it?

**Comment by arstrube** [comment] 2015-03-11 09:08
I tried a really old commit, which still included a .mak and a .bat for a command line build. Now I seem to be lacking a Windows SDK...

Also, it seems to be impossible to still get VC98 - only "fake" links (leading to VS2013) and suspicious downloads...

**Comment by arstrube** [comment] 2015-03-11 10:41
@PaulBussmann - correction. I succeded in setting up VC2005. This would need to convert the .dsw / .dsp files, but it refuses to do so claiming they are corrupt.

**Comment by arstrube** [comment] 2015-03-11 10:45
@PaulBussmann 
(1) The .dsp has Unix line endings. Needs to be Windows. Also, need to make sure in Git config that it is always Windows.
(2) All CppUTestExt sources and tests appear to be missing still.
(3) No linker Problem with VS2005 (which, admittedly, isn't VC6, but still...

**Comment by arstrube** [comment] 2015-03-11 10:50
Added a pull request for (1).

**Comment by arstrube** [comment] 2015-03-11 10:51
(4) It's also still lacking all tests (which used to be in AllTests.dsp).

**Comment by arstrube** [comment] 2015-03-11 10:53
We need to re-instate AllTests.dsp rather than remove it from the solution. It got lost along the way. I'll put it back.
@PaulBussmann kindly make sure that it contains ALL tests, e.g. including the CppUTestExt directory.

**Comment by arstrube** [comment] 2015-03-11 12:32
@PaulBussmann unfortunately, not having VC6, it is hard for me to contribute. But I can import the result into VC2005 and see whether it looks like it should...

Apart from adding all the new files, it seems the post-build step to run the application is missing in AllTests.dsp.

**Comment by arstrube** [comment] 2015-03-11 15:16
Amazing ... there are CDs on sale on Ebay for EUR 250.00 to EUR 500.00 and from very dubious sources to say the least :P

**Comment by Andne** [comment] 2015-03-11 15:20
I found one of the old Platform SDKs on MSDN, but I haven't had a chance to see if it contains the compiler or not.  Other than that, all I've seen are various 'questionable' download sources online.

**Comment by arstrube** [comment] 2015-03-11 16:38
I found the old hag somewhere. 

@PaulBussmann be warned - there is now a new error in one of the test .cpp's. Going to post now-now...

**Comment by arstrube** [comment] 2015-03-11 16:48
It takes exception to:
```c++
char* nonArrayMemoryNoThrow = new (std::nothrow) char[10];
```
saying:
```
...\memoryleakwarningtest.cpp(321) : error C2661: 'new[]' : no overloaded function takes 2 parameters
```

**Comment by arstrube** [comment] 2015-03-11 16:59
And there is more....

@basvodde - Am I having double vision, or why didn't any other compiler complain:
```c++
void setIntData_c(const char* name, int value)
{
    return currentMockSupport->setData(name, value);
}
```
What gives?

**Comment by basvodde** [comment] 2015-03-12 01:22
I think I have some vague recollection that this was a problem in VS6. There should be one of those by default in C++, but in VS6 when you override the operator new, then it hides the default... at least I think that is what happened.

I remember we added them at some point and deleted them again as adding them also caused trouble with the operator new #define and how to call them. You can play with adding them a bit and see how far you get (and how it will work on other compilers)

**Comment by arstrube** [comment] 2015-03-12 09:09
Err, actually this is a bit over my head... also, I still have no idea to add forced includes to pre-2005 VS projects?

**Comment by basvodde** [comment] 2015-03-12 10:12
Haven't used VS6 for 15 years, so I'm afraid I won't be able to help :)

**Comment by arstrube** [comment] 2015-03-12 10:54
I think fixing this is actually not feasable. The last CppUTest version that worked was 3.4 (with some trivial fixes).

But, having said that, "as is" it included none of the extensions.

As soon as I add the extensions, and fix a few other trivial errors, it will compile, but then report tons of memory leaks and wind up crashing, just like the current version does (plus, as of 3.5 there is the new[] problem as a "bonus".

@PaulBussmann - if using CppUTest without extensions would be an option, you might get it to work.

@basvodde - I don't think we can really support VC6. We should probably fix whatever minor issues there are, though (like void returning a value etc)

**Comment by arstrube** [comment] 2015-03-12 11:09
It appears that VC6 has never, ever, been used with CppUTest extensions.

Everything considered, maybe turning off memory leak detection wouldn't be such a bad thing in this situation...

**Comment by PaulBussmann** [comment] 2015-03-12 22:44
@basvodde @arstrube I'm fine with turning off memory leak detection. Thank you very much anyway for taking your time and the instant support!

**Comment by basvodde** [comment] 2015-03-13 01:53
Yeah, I understand. It would be great if we could fix it with it on though, as I'm sure you aren't the only VS6 user left ;)

**Comment by basvodde** [comment] 2015-03-13 02:22
@arstrube I do think we want to try to keep support for things like VS6. One reason is that a lot of the errors discovered there are probably the same for other older compilers. Almost every embedded project I've worked on had older compilers, so trying to keep the code compiling under any reasonable C++ compiler is one of the goals of CppUTest (from my perspective). Though, as you don't have VS6 yourself, it would be hard to do that. I appreciate your attempts though!

**Comment by arstrube** [comment] 2015-03-13 05:58
@basvodde - I agree with your thinking. I even scavanged an old copy of VC6 and got it to work. The problem is that, ever since CppUTest extensions have been around, apparantly nobody ran them past VC6. The problems don't look trivial to me. If we are lucky though, they are limited to memory leak detection. So we could "support" VC6 by disabling it by default.

@PaulBussmann have you actually tried compiling and running the extensions with memory leak detection disabled? If that worked, it wouldn't be so bad.

**Comment by arstrube** [comment] 2015-03-13 13:25
You asked for it -- you got it!  Nice Juicy Bugs for your inspection, @basvodde.

So far, this fixes MockSupportTest.cpp and MockExpectedCall.cpp.

More to come...

**Comment by arstrube** [comment] 2015-03-15 16:39
@basvodde - my pull requests #516, #517 and #518 should take care of any VC98 problems. Any reason why they can't be merged?

@PaulBussmann I didn't see some of the linker problems you described; I disabled the memory leak warnings (since I don't know how to fix the new[] compilation problem for two of the CppUTestExt tests) and all tests CppUTest as well as CppUTestExt are fixed up so they are compatible with VC6.

**Comment by basvodde** [comment] 2015-03-16 06:38
All fixed now?

**Comment by arstrube** [comment] 2015-03-23 08:31
@PaulBussmann all well?

**Comment by PaulBussmann** [comment] 2015-03-24 18:08
I'm away for some days. I'll check when I am back.

**Comment by arstrube** [comment] 2016-05-12 13:58
@PaulBussmann ?

**Comment by PaulBussmann** [comment] 2016-05-13 15:22
Last time I tried, it was OK. Sorry for not giving feed-back earlier.

**Closed** 2016-05-16 23:17 UTC
