### ISSUE TITLE
compilation failure on Windows mingw64

### ISSUE THREAD

**Issue by bikeNomad** [cpputest/cpputest#1232] opened 2019-08-21 20:58 UTC
I'm trying to install CppUnit on a Windows system that has mingw64 installed.
I just cloned the github repo, did an `autoreconf .. -i`, then `../configure`, and `make`.
I got this result:
```
$ make
make  all-am
make[1]: Entering directory '/home/ned/src/cpputest/cpputest_build'
g++ -DHAVE_CONFIG_H -I. -I..   -include ../include/CppUTest/MemoryLeakDetectorMallocMacros.h -I ../include     -nostdinc++  -Wno-missing-exception-spec -include ../include/CppUTest/MemoryLeakDetectorNewMacros.h  -Wno-c++14-compat -Wno-c++11-long-long -Wno-long-long -Wall -Wextra -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -pedantic -Wsign-conversion -Woverloaded-virtual -Wno-disabled-macro-expansion -Wno-padded -Wno-reserved-id-macro -Wno-keyword-macro -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -Wno-old-style-cast   -g -O2 -MT src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o -MD -MP -MF src/CppUTest/.deps/lib_libCppUTest_a-CommandLineArguments.Tpo -c -o src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o `test -f 'src/CppUTest/CommandLineArguments.cpp' || echo '../'`src/CppUTest/CommandLineArguments.cpp
In file included from ../include/CppUTest/Utest.h:34:0,
                 from ../include/CppUTest/TestHarness.h:39,
                 from ../src/CppUTest/CommandLineArguments.cpp:29:
../include/CppUTest/SimpleString.h:183:36: error: 'nullptr_t' in namespace 'std' does not name a type
 SimpleString StringFrom(const std::nullptr_t value);
                                    ^~~~~~~~~
cc1plus.exe: warning: unrecognized command line option '-Wno-weak-vtables'
cc1plus.exe: warning: unrecognized command line option '-Wno-exit-time-destructors'
cc1plus.exe: warning: unrecognized command line option '-Wno-global-constructors'
cc1plus.exe: warning: unrecognized command line option '-Wno-keyword-macro'
cc1plus.exe: warning: unrecognized command line option '-Wno-reserved-id-macro'
cc1plus.exe: warning: unrecognized command line option '-Wno-disabled-macro-expansion'
cc1plus.exe: warning: unrecognized command line option '-Wno-c++11-long-long'
cc1plus.exe: warning: unrecognized command line option '-Wno-missing-exception-spec'
make[1]: *** [Makefile:1601: src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o] Error 1
make[1]: Leaving directory '/home/ned/src/cpputest/cpputest_build'
make: *** [Makefile:926: all] Error 2
```

I then added this snippet to the top of `SimpleString.h`:
```
namespace std
{
   typedef decltype(nullptr) nullptr_t;
}
```
and ran `make` again.
(I realize that this isn't a real fix but I wanted to see if that was all that was the problem).
This time I did get a full compile (though there were more complaints about unrecognized warning options and unknown `printf` conversion type characters (`%lld` etc.).

Running `make check` gave this result:
```
PASS: CppUTestTests.exe
FAIL: CppUTestExtTests.exe
============================================================================
Testsuite summary for CppUTest 3.8
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/cpputest/cpputest
============================================================================
```
The only failure reported in `test-suite.log` was:
```
../tests/CppUTestExt/IEEE754PluginTest.cpp:123: error: Failure in TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
        CHECK(IEEE754ExceptionsPlugin::checkIeee754OverflowExceptionFlag()) failed
```

`g++ --version` reports:
```
g++.exe (Rev1, Built by MSYS2 project) 7.2.0
```

**Comment by keith-at-spacee** [comment] 2019-08-21 21:16
Hi Ned.  I'm also using Msys2.  But I've carefully applied updates to it, per https://github.com/msys2/msys2/wiki/MSYS2-installation , section III. Updating Packages.  Consequently, I have the latest gcc (9.1.0), but have no problems like you describe.  I got this result.  
```
$ make check
make  CppUTestTests.exe CppUTestExtTests.exe
make[1]: Entering directory '/home/keith/e2_studio/workspace/CppUTest'
make[1]: 'CppUTestTests.exe' is up to date.
make[1]: 'CppUTestExtTests.exe' is up to date.
make[1]: Leaving directory '/home/keith/e2_studio/workspace/CppUTest'
make  check-TESTS
make[1]: Entering directory '/home/keith/e2_studio/workspace/CppUTest'
make[2]: Entering directory '/home/keith/e2_studio/workspace/CppUTest'
PASS: CppUTestTests.exe
PASS: CppUTestExtTests.exe
============================================================================
Testsuite summary for CppUTest 3.8
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory '/home/me/e2_studio/workspace/CppUTest'
make[1]: Leaving directory '/home/me/e2_studio/workspace/CppUTest'

me@My-Razer-Laptop MSYS ~/e2_studio/workspace/CppUTest
$ g++ --version
g++ (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by keith-at-spacee** [comment] 2019-08-21 21:30
What are the results of ``$ make tdd`` ? I get 
```
$ make tdd
./CppUTestTests
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
................!....!.!......!.....!..!..!..!..!.
.!..!..!..!..!..!..!..!..!........!..!..!..!..!..!
..!..!..!..!..!..!..!........!..!..!..!..!..!..!..
!..!..!..........................!........!....
OK (647 tests, 604 ran, 1129 checks, 43 ignored, 0 filtered out, 12 ms)

./CppUTestExtTests
.................!!...............................
..........!.......................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
...............................................
OK (447 tests, 444 ran, 1395 checks, 3 ignored, 0 filtered out, 42 ms)
```

**Comment by bikeNomad** [comment] 2019-08-21 21:46
I get:
```
$ make tdd
./CppUTestTests
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........................................!.........
..................................................
.....................!..!..!..!..!..!..!....!.!...
...!.....!..!..!..!..!..!..!..!..!..!..!..!...!..!
.......!..!...!..!..!..!..!..!..!..!..!..!..!..!..
!........!..!..!..!..!..!..!..!..!..!.............
............!........!....
OK (726 tests, 674 ran, 1315 checks, 52 ignored, 0 filtered out, 10 ms)

./CppUTestExtTests
.................!
../tests/CppUTestExt/IEEE754PluginTest.cpp:123: error: Failure in TEST(FE__with_Plugin, should_not_fail_again_when_test_has_already_failed)
        CHECK(IEEE754ExceptionsPlugin::checkIeee754OverflowExceptionFlag()) failed

................................
...........!......................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..........
Errors (1 failures, 510 tests, 508 ran, 1610 checks, 2 ignored, 0 filtered out, 50 ms)
```

**Comment by keith-at-spacee** [comment] 2019-08-21 21:53
I just repeated your first results when I used the mingw64 shell instead of the msys2 shell!
```
$ make
make  all-am
make[1]: Entering directory '/home/keith/src/cpputest/cpputest_build'
g++ -DHAVE_CONFIG_H -I. -I..   -include ../include/CppUTest/MemoryLeakDetectorMallocMacros.h -I ../include     -nostdinc++  -Wno-missing-exception-spec -include ../include/CppUTest/MemoryLeakDetectorNewMacros.h  -Wno-c++14-compat -Wno-c++11-long-long -Wno-long-long -Wall -Wextra -Wshadow -Wswitch-default -Wswitch-enum -Wconversion -pedantic -Wsign-conversion -Woverloaded-virtual -Wno-disabled-macro-expansion -Wno-padded -Wno-reserved-id-macro -Wno-keyword-macro -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -Wno-old-style-cast   -g -O2 -MT src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o -MD -MP -MF src/CppUTest/.deps/lib_libCppUTest_a-CommandLineArguments.Tpo -c -o src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o `test -f 'src/CppUTest/CommandLineArguments.cpp' || echo '../'`src/CppUTest/CommandLineArguments.cpp
In file included from ../include/CppUTest/Utest.h:34,
                 from ../include/CppUTest/TestHarness.h:39,
                 from ../src/CppUTest/CommandLineArguments.cpp:29:
../include/CppUTest/SimpleString.h:183:36: error: 'nullptr_t' in namespace 'std' does not name a type
  183 | SimpleString StringFrom(const std::nullptr_t value);
      |                                    ^~~~~~~~~
cc1plus.exe: warning: unrecognized command line option '-Wno-weak-vtables'
cc1plus.exe: warning: unrecognized command line option '-Wno-exit-time-destructors'
cc1plus.exe: warning: unrecognized command line option '-Wno-global-constructors'
cc1plus.exe: warning: unrecognized command line option '-Wno-keyword-macro'
cc1plus.exe: warning: unrecognized command line option '-Wno-reserved-id-macro'
cc1plus.exe: warning: unrecognized command line option '-Wno-disabled-macro-expansion'
cc1plus.exe: warning: unrecognized command line option '-Wno-c++11-long-long'
cc1plus.exe: warning: unrecognized command line option '-Wno-missing-exception-spec'
make[1]: *** [Makefile:1703: src/CppUTest/lib_libCppUTest_a-CommandLineArguments.o] Error 1
make[1]: Leaving directory '/home/keith/src/cpputest/cpputest_build'
make: *** [Makefile:1022: all] Error 2
```
with 
```
$ g++ --version
g++.exe (Rev1, Built by MSYS2 project) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bikeNomad** [comment] 2019-08-21 21:57
> I just repeated your first results when I used the mingw64 shell instead of the msys2 shell!

Yes, I was using the mingw64 shell.

**Comment by keith-at-spacee** [comment] 2019-08-21 21:59
Visiting the same folder using the Msys2 shell gives the same result.  I think I built the working version using Cmake.

**Comment by keith-at-spacee** [comment] 2019-08-21 22:07
No, $CMake CMakeLists.txt also fails!

**Comment by keith-at-spacee** [comment] 2019-08-21 22:29
The version of CppUTest I showed working is older than the current version from GitHub, by at least 1 week.  It seems the newest version does not build, as we both have noted.

**Comment by basvodde** [comment] 2019-08-22 01:37
Weird error, but good find. I don't think we want to use nullptr_t in CppUTest. That needs to be removed.

**Comment by keith-at-spacee** [comment] 2019-08-22 15:32
This is a duplicate of earlier issue 1130, https://github.com/cpputest/cpputest/issues/1130

**Closed** 2020-04-23 04:12 UTC
